name: Ryan Colwell
description: Ryan Colwell's blog on software development.
title: Some Title
tagline: Phenomenal Technical Powers -- Itty-Bitty Working Space
footerline: I hate the sea and everything in it.
highlighter: Pygments
markdown: redcarpet
markdown_ext:  markdown,mkd,mkdn,md


author:
 name: Ryan Colwell
 email: ryan g colwell at the gmailz dot com
 github: ryanco
 twitter: ryangcolwell


url: http://ryancolwell.com
