name: Ryan Colwell
title: Some Title
tagline: Phenomenal Technical Powers -- Itty-Bitty Working Space
markdown: redcarpet
pygments: true


author:
 name: Ryan Colwell
 email: ryan g colwell at the gmailz dot com
 github: ryanco
 twitter: ryangcolwell
 
 
url: http://ryanco.github.io
